In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [4]:
data = {
    'Weight': [79, 69, 73, 95, 82, 55, 69, 71, 64, 69],
    'Height': [1.80, 1.68, 1.82, 1.70, 1.87, 1.55, 1.50, 1.78, 1.67, 1.64],
    'Age': [35, 39, 25, 60, 27, 18, 89, 42, 16, 52],
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Male',
               'Female', 'Female', 'Female', 'Female', 'Female']
}
df = pd.DataFrame(data)
df

   Weight  Height  Age  Gender
0      79    1.80   35    Male
1      69    1.68   39    Male
2      73    1.82   25    Male
3      95    1.70   60    Male
4      82    1.87   27    Male
5      55    1.55   18  Female
6      69    1.50   89  Female
7      71    1.78   42  Female
8      64    1.67   16  Female
9      69    1.64   52  Female

In [5]:
#Encoder Gender

df['Gender'] = df['Gender'].map({'Male':0, 'Female':1})
df

   Weight  Height  Age  Gender
0      79    1.80   35       0
1      69    1.68   39       0
2      73    1.82   25       0
3      95    1.70   60       0
4      82    1.87   27       0
5      55    1.55   18       1
6      69    1.50   89       1
7      71    1.78   42       1
8      64    1.67   16       1
9      69    1.64   52       1

In [6]:
# Separate Independent and dependent variables

X = df[['Height', 'Age', 'Gender']]
y = df['Weight']
print("Independent Variables (X):")
print(X)

print("\nDependent Variable (y):")
print(y)

Independent Variables (X):
   Height  Age  Gender
0    1.80   35       0
1    1.68   39       0
2    1.82   25       0
3    1.70   60       0
4    1.87   27       0
5    1.55   18       1
6    1.50   89       1
7    1.78   42       1
8    1.67   16       1
9    1.64   52       1

Dependent Variable (y):
0    79
1    69
2    73
3    95
4    82
5    55
6    69
7    71
8    64
9    69
Name: Weight, dtype: int64

In [7]:
#Spliting the dataset into training and testing

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state=42
)

In [8]:
# Linear regression model

model = LinearRegression()
model.fit(X_train, y_train)
print("Model training completed successfully.")

Model training completed successfully.

In [9]:
print("Intercept:", model.intercept_)
print("\n Coefficients:")
for feature, coefficient in zip(X.columns, model.coef_):
    print(f"{feature}:{coefficient}")

Intercept: 11.567901240452528

 Coefficients:
Height:32.83533630032698
Age:0.31729474176080896
Gender:-14.623118479712073

In [11]:
y_pred = model.predict(X_test)

print("\nActual vs Predicted:")
comparison = pd.DataFrame({
    'Actual Weight': y_test.values,
    'Predicted Weight': np.round(y_pred, 2)
})
print(comparison)


# 8. Evaluation Metrics
#----------------------------------------------
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("\nPerformance Metrics:")
print("--------------------")
print(f"MAE  : {mae:.4f}")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R²   : {r2:.4f}")


# 9. Predict Weight for New Person
# --------------------------------------------------
new_person = pd.DataFrame({
    'Height': [1.75],
    'Age': [30],
    'Gender': [0]  # Female
})
predicted_weight = model.predict(new_person)

print("\nNew Person:")
print("Height = 1.75 m")
print("Age = 30")
print("Gender = Female")

print(f"\nPredicted Weight = {predicted_weight[0]:.2f} kg")

Actual vs Predicted:
   Actual Weight  Predicted Weight
0             64             56.86
1             69             79.11

Performance Metrics:
--------------------
MAE  : 8.6246
MSE  : 76.5779
RMSE : 8.7509
R²   : -11.2525

New Person:
Height = 1.75 m
Age = 30
Gender = Female

Predicted Weight = 78.55 kg